In [1]:
import pandas as pd
import numpy as np

In [2]:
#1
pd.__version__

'2.2.3'

In [5]:
#2
df = pd.read_csv('laptops.csv')
len(df)

2160

In [6]:
#3
unique = df["Brand"].unique()
len(unique)

27

In [7]:
#4
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [8]:
#5
df_dell = df[df['Brand'] == "Dell"]
df_dell['Final Price'].max()

3936.0

In [9]:
#6
df['Screen'].median()

15.6

In [10]:
counts = df['Screen'].value_counts()
df['Screen'] = df['Screen'].fillna(counts.index[0])

In [11]:
df['Screen'].median()

15.6

In [12]:
#7
df_new = df[df['Brand'] == "Innjoo"]
df_arr = df_new.loc[:, ['RAM', 'Storage', 'Screen']] 

In [13]:
df_arr = df_arr.apply(pd.to_numeric, errors='coerce')
X = df_arr.values
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [14]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
XTX_inv_XT = XTX_inv @ X.T
w = XTX_inv_XT @ y
print(w)

[45.58076606  0.42783519 45.29127938]


In [15]:
sum_w = np.sum(w)
print(sum_w)

91.29988062995815
